# HEVD appveyor configuration

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.0.{build}

# branches to build
branches:
  # whitelist
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\hevd

# scripts that are called at very beginning, before repo cloning
init:
- cmd: git config --global core.autocrlf input

# this is how to allow failing jobs in the matrix
# matrix:
#   fast_finish: true

# script to build the driver
build_script:
- cmd: cd c:\projects\hevd\Builder
- cmd: '%COMSPEC% /c Build_HEVD_All.bat'

# disable test
test: off

# disable deployment
deploy: off